module.exports = [
    {
        userName: 'JaneSmith456',
        email: 'janesmith@example.com',
        password: 'securePassword!',
        bio: 'UX/UI designer',
        aboutMe: 'I am a UX/UI designer passionate about creating exceptional digital experiences. My goal is to blend aesthetics and functionality to deliver innovative interface solutions.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671118.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Premium',
    },
    {
        userName: 'JohnDoe789',
        email: 'johndoe@example.com',
        password: 'password123',
        bio: 'Fullstack developer',
        aboutMe: 'Fullstack developer experienced in building complete web applications. I love tackling technical challenges and finding efficient solutions to complex problems.',
        image: 'https://img.freepik.com/fotos-premium/personaje-dibujos-animados-fondo-azul-generado-ia_1029473-129016.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'AliceJohnson101',
        email: 'alicejohnson@example.com',
        password: 'alicepassword',
        bio: 'Data scientist',
        aboutMe: 'Data scientist with a focus on advanced analytics and predictive modeling. My passion is transforming data into actionable insights for informed decision-making.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671138.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'BobBrown202',
        email: 'bobbrown@example.com',
        password: 'bobbypassword',
        bio: 'Project manager',
        aboutMe: 'Project manager with experience in leading teams and coordinating resources to deliver projects on time and within budget. I specialize in strategic planning and efficient execution.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671116.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'CharlieDavis303',
        email: 'charliedavis@example.com',
        password: 'charliedpassword',
        bio: 'Backend developer',
        aboutMe: 'Backend developer with a strong understanding of system architecture and databases. I am dedicated to building robust and scalable solutions for web applications.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-linea_23-2151303048.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'DanaEvans404',
        email: 'danaevans@example.com',
        password: 'danapassword',
        bio: 'Graphic designer',
        aboutMe: 'Creative graphic designer with an eye for detail and a passion for visual design. My goal is to create impactful graphics that effectively communicate messages.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-linea_23-2151303063.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'EvanGarcia505',
        email: 'evangarcia@example.com',
        password: 'evanpassword',
        bio: 'Marketing specialist',
        aboutMe: 'Marketing specialist with experience in digital strategies and advertising campaigns. I focus on driving brand growth through innovative marketing techniques.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671122.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'FionaHarris606',
        email: 'fionaharris@example.com',
        password: 'fionapassword',
        bio: 'Sales manager',
        aboutMe: 'Sales manager with a focus on maximizing revenue and developing long-term client relationships. My experience centers around sales team management and strategy.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-linea_23-2151303097.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'GeorgeIbrahim707',
        email: 'georgeibrahim@example.com',
        password: 'georgepassword',
        bio: 'Frontend developer',
        aboutMe: 'Frontend developer with a strong design sense and solid web technology experience. I specialize in creating intuitive and engaging user interfaces.',
        image: 'https://img.freepik.com/psd-gratis/render-3d-personaje-avatar_23-2150611765.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'HannahJackson808',
        email: 'hannahjackson@example.com',
        password: 'hannahpassword',
        bio: 'SEO specialist',
        aboutMe: 'SEO specialist focused on improving search engine visibility. My passion is helping businesses achieve their organic traffic and online performance goals.',
        image: 'https://img.freepik.com/psd-gratis/3d-ilustracion-persona-gafas_23-2149436185.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'IanKing909',
        email: 'ianking@example.com',
        password: 'ianpassword',
        bio: 'Content writer',
        aboutMe: 'Content writer with a talent for crafting engaging and persuasive texts. My goal is to communicate ideas clearly and effectively, adapting style to the target audience.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671126.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'JulieLopez010',
        email: 'julielopez@example.com',
        password: 'juliepassword',
        bio: 'HR manager',
        aboutMe: 'HR manager with experience in talent management and organizational development. I focus on building effective teams and fostering a positive work environment.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671138.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'KyleMartin111',
        email: 'kylemartin@example.com',
        password: 'kylepassword',
        bio: 'Business analyst',
        aboutMe: 'Business analyst with a focus on process optimization and data-driven decision making. My goal is to improve efficiency and effectiveness in business operations.',
        image: 'https://img.freepik.com/fotos-premium/personaje-dibujos-animados-fondo-azul-generado-ia_1029473-129016.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'LauraNelson212',
        email: 'lauranelson@example.com',
        password: 'laurapassword',
        bio: 'Accountant',
        aboutMe: 'Accountant with experience in financial management and reporting. I am dedicated to ensuring accuracy and integrity in business finances.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-linea_23-2151303063.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'MikeOlsen313',
        email: 'mikeolsen@example.com',
        password: 'mikepassword',
        bio: 'Software engineer',
        aboutMe: 'Software engineer with experience in developing custom software solutions. I enjoy solving complex problems through programming and system engineering.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-avatar-o-perfil-humano_23-2150671159.jpg?ga=GA1.1.809440281.1720916925',
        planName: 'Free',
    },
    {
        userName: 'IvanBell',
        email: 'ivan@bell.com',
        password: 'ivan123',
        bio: 'Software engineer',
        aboutMe: 'Software engineer with a focus on creating innovative applications and technical management. As an admin, I also oversee system maintenance and integrity.',
        image: 'https://img.freepik.com/psd-premium/3d-render-avatar-dibujos-animados-aislado_570939-51.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
    {
        userName: 'Luis Diaz',
        email: 'luis@diaz.com',
        password: 'luis123',
        bio: 'Accountant',
        aboutMe: 'Software engineer with a focus on creating innovative applications and technical management. As an admin, I also oversee system maintenance and integrity.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-persona-calva-gafas_23-2149436184.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
    {
        userName: 'Gaston Ibarra',
        email: 'gaston@ibarra.com',
        password: 'gaston123',
        bio: 'Business analyst',
        aboutMe: 'Business analyst with skills in identifying opportunities for improvement and optimization. My administrative role includes overseeing data analysis and business strategy implementation.',
        image: 'https://img.freepik.com/fotos-premium/personaje-3d-personas-cerca-retrato-sonriendo-bonito-3d-avatar-o-icono_43969-22737.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
    {
        userName: 'Miguel Linares',
        email: 'miguel@linares.com',
        password: 'miguel123',
        bio: 'HR manager',
        aboutMe: 'HR manager with comprehensive experience in personnel management and organizational development. In my administrative role, I focus on talent strategy and organizational well-being.',
        image: 'https://img.freepik.com/psd-gratis/ilustracion-3d-persona-gafas-cabeza-medio-rapada_23-2149436187.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
    {
        userName: 'Maria Sol Iha',
        email: 'mariasol@iha.com',
        password: 'marial123',
        bio: 'Content writer',
        aboutMe: 'Content writer with a passion for creating persuasive and strategic texts. As an admin, I also manage content planning and execution to maximize impact.',
        image: 'https://img.freepik.com/psd-gratis/render-3d-personaje-avatar_23-2150611716.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
    {
        userName: 'Maximiliano Altamirano',
        email: 'maximiliano@altamirano.com',
        password: 'maximilianol123',
        bio: 'SEO specialist',
        aboutMe: 'SEO specialist focused on enhancing online presence and search engine performance. In my administrative role, I oversee SEO strategies and content optimizations.',
        image: 'https://img.freepik.com/fotos-premium/personaje-3d-personas-cerca-retrato-sonriendo-bonito-3d-avatar-o-icono_43969-20056.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
    {
        userName: 'Aldana Delgado',
        email: 'aldana@delgado.com',
        password: 'aldana123',
        bio: 'UI/UX designer',
        aboutMe: 'UI/UX designer with experience in creating intuitive interfaces and exceptional user experiences. As an admin, I also manage design projects and product development.',
        image: 'https://img.freepik.com/psd-gratis/3d-ilustracion-persona-cabello-largo_23-2149436197.jpg?ga=GA1.1.809440281.1720916925',
        role: 'admin',
    },
];
